name: Deploy to EC2 on Dev Branch Push

on:
  push:
    branches:
      - dev  # trigger deployment on push to 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 host to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: SSH and deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/django-docker-ec2 || git clone https://github.com/harshadakhorgade/django-docker-ec2.git ~/django-docker-ec2 && cd ~/django-docker-ec2
          git pull origin dev
          docker-compose down
          docker-compose build
          docker-compose up -d
        EOF
